config/routes.rb
Rails.application.routes.draw do
  resources :shortners
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'shortners#new' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/shortner.rb
class Shortner < ApplicationRecord

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/shortners_controller.rb
class ShortnersController < ApplicationController
  before_action :set_shortner, only: [:show, :edit, :update, :destroy]

  # GET /shortners
  # GET /shortners.json
  def index
    @shortners = Shortner.all
  end

  # GET /shortners/1
  # GET /shortners/1.json
  def show
  end

  # GET /shortners/new
  def new
    @shortner = Shortner.new
  end

  # GET /shortners/1/edit
  def edit
  end

  # POST /shortners
  # POST /shortners.json
  def create
    @shortner = Shortner.new(shortner_params)

    respond_to do |format|
      if @shortner.save
        format.html { redirect_to @shortner, notice: 'Shortner was successfully created.' }
        format.json { render :show, status: :created, location: @shortner }
      else
        format.html { render :new }
        format.json { render json: @shortner.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shortners/1
  # PATCH/PUT /shortners/1.json
  def update
    respond_to do |format|
      if @shortner.update(shortner_params)
        format.html { redirect_to @shortner, notice: 'Shortner was successfully updated.' }
        format.json { render :show, status: :ok, location: @shortner }
      else
        format.html { render :edit }
        format.json { render json: @shortner.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shortners/1
  # DELETE /shortners/1.json
  def destroy
    @shortner.destroy
    respond_to do |format|
      format.html { redirect_to shortners_url, notice: 'Shortner was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shortner
      @shortner = Shortner.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shortner_params
      params.require(:shortner).permit(:longurl, :shorturl, :active)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shortners_helper.rb
module ShortnersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Urlshortnr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shortners/_form.html.erb
<%= form_with(model: shortner, local: true) do |form| %>
  <% if shortner.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(shortner.errors.count, "error") %> prohibited this shortner from being saved:</h2>

      <ul>
      <% shortner.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :longurl %>
    <%= form.text_field :longurl, id: :shortner_longurl %>
  </div>

  <div class="field">
    <%= form.label :shorturl %>
    <%= form.text_field :shorturl, id: :shortner_shorturl %>
  </div>

  <div class="field">
    <%= form.label :active %>
    <%= form.check_box :active %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/shortners/edit.html.erb
<h1>Editing Shortner</h1>

<%= render 'form', shortner: @shortner %>

<%= link_to 'Show', @shortner %> |
<%= link_to 'Back', shortners_path %>

app/views/shortners/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Shortners</h1>

<table>
  <thead>
    <tr>
      <th>Longurl</th>
      <th>Shorturl</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shortners.each do |shortner| %>
      <tr>
        <td><%= shortner.longurl %></td>
        <td><%= link_to shortner.shorturl, shortner.longurl %></td>
        <td><%= link_to 'Show', shortner %></td>
        <td><%= link_to 'Edit', edit_shortner_path(shortner) %></td>
        <td><%= link_to 'Destroy', shortner, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shortner', new_shortner_path %>

app/views/shortners/new.html.erb
<h1>New Shortner</h1>

<%= render 'form', shortner: @shortner %>

<%= link_to 'Back', shortners_path %>

app/views/shortners/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Longurl:</strong>
  <%= @shortner.longurl %>
</p>

<p>
  <strong>Shorturl:</strong>
  <%= link_to @shortner.shorturl, @shortner.longurl %>
</p>

<p>
  <strong>Active:</strong>
  <%= @shortner.active %>
</p>


<%= link_to 'Edit', edit_shortner_path(@shortner) %> |
<%= link_to 'Back', shortners_path %>